# Part 8 - User interface. Facts read: frontend/app/chat/page.tsx (102 lines) renders ChatSidebar, MessageBubble (inline edit/regenerate, copy, feedback, citations, voice output) and ChatComposer
# (voice input, push-to-talk, starter suggestions). Components with NO importer in frontend/app, components or lib: RegenerateButton, RetryButton, EditQuestion, ShareConversation, SuggestedQuestions,
# FollowUpQuestions, VoiceMessageList, VoiceSettings, Telephony (only its test), AudioPermission. Backend routes exist for retry, share, visibility and export (api/routers/conversations.py).
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
CHAT = "frontend/app/chat/page.tsx + frontend/lib/useRealChat.ts"
ORPH = "the UI component exists but no page imports it"
VOICE = "api/services/voice.py (Whisper/Deepgram STT, ElevenLabs/Google TTS), api/routers/voice.py"
V = {
"8.1.1": (VC, "MEDIUM", "SSE streaming api/routers/chat_stream.py, api/services/streaming.py; consumer " + CHAT, "tests/test_streaming.py, tests/test_stream_response_tools.py, tests/test_p1_chat_stream_refusal.py", "tenant isolation fixed in P0", "no browser end-to-end run", "LLM provider for a real stream", "INFO", "none"),
"8.1.2": (VC, "HIGH", "frontend/components/ChatMarkdown.tsx (rehype-sanitize per project rules), MessageContent.tsx; api/services/markdown_renderer.py", "frontend/components/ChatMarkdown.test.tsx, tests/test_markdown_renderer.py", "sanitised markdown", "none found", "none", "INFO", "none"),
"8.1.3": (VC, "MEDIUM", "code highlighting in ChatMarkdown.tsx and api/services/code_highlighter.py", "tests/test_code_highlighter.py, ChatMarkdown.test.tsx", "none", "none found", "none", "INFO", "none"),
"8.1.4": (VC, "MEDIUM", "CitationList rendered by frontend/components/MessageBubble.tsx", "frontend component tests partial", "none", "none found", "none", "INFO", "none"),
"8.1.5": (VC, "HIGH", "CopyButton used by MessageBubble.tsx and ChatMarkdown.tsx", "ChatMarkdown.test.tsx", "none", "none found", "none", "INFO", "none"),
"8.1.6": (VC, "HIGH", "regenerate button in MessageBubble.tsx:80 -> useRealChat regenerate; POST /conversations/{id}/messages/{id}/regenerate", "tests/test_message_actions.py", "none", "standalone RegenerateButton.tsx is unused", "none", "INFO", "none"),
"8.1.7": (VC, "HIGH", "inline edit in MessageBubble.tsx:45 -> useRealChat editMessage; POST .../edit and edit-history routes", "tests/test_message_actions.py", "none", "standalone EditQuestion.tsx is unused", "none", "INFO", "none"),
"8.1.8": (PI, "HIGH", "backend POST /conversations/{id}/messages/{id}/retry (conversations.py:435); RetryButton.tsx " + ORPH, "tests/test_message_actions.py", "none", "no retry action in the chat UI (regenerate is separate)", "none", "LOW", "wire RetryButton or document regenerate as the retry"),
"8.1.9": (VC, "MEDIUM", "frontend/components/FeedbackButtons.tsx used by MessageBubble.tsx; api/routers/feedback.py", "feedback tests (test_p1_*/feedback files to confirm)", "org-scoped", "reason and comment fields in the UI not confirmed", "none", "LOW", "confirm reason/comment capture"),
"8.1.10": (VC, "HIGH", "ChatSidebar.tsx + ConversationList.tsx; api/routers/conversations.py", "tests/test_conversations.py, tests/test_conversation_idor.py, tests/test_p0_chat_conversation_isolation.py", "IDOR and isolation tests", "none found", "none", "INFO", "none"),
"8.1.11": (VC, "HIGH", "RenameConversation used by ConversationItem.tsx; PATCH /conversations/{id}", "tests/test_conversation_management.py", "none", "none found", "none", "INFO", "none"),
"8.1.12": (VC, "HIGH", "ConversationSearch used by ChatSidebar.tsx; GET /conversations/search", "tests/test_conversation_management.py", "scoped to the user", "none found", "none", "INFO", "none"),
"8.1.13": (VC, "HIGH", "DeleteConversation used by ConversationItem.tsx; DELETE, restore and permanent routes", "tests/test_conversation_management.py", "none", "none found", "none", "INFO", "none"),
"8.1.14": (PI, "HIGH", "backend export PDF/DOCX/JSON/Markdown (conversations.py:256-291, api/services/conversation_export.py)", "tests/test_conversation_export.py", "owner-scoped", "no export control in the chat UI; PDF needs weasyprint system libraries on the host", "weasyprint libraries", "LOW", "add export menu; confirm weasyprint in the Docker image"),
"8.1.15": (PI, "HIGH", "backend POST /conversations/{id}/share and GET /share/{token} (conversation_shares.py); ShareConversation.tsx " + ORPH, "tests/test_conversation_sharing.py", "token-based sharing; public read of shared content to review", "no share control in the chat UI", "none", "LOW", "wire ShareConversation"),
"8.1.16": (PI, "HIGH", "backend PATCH /conversations/{id}/visibility and GET /conversations/public (conversations.py:148,329)", "tests/test_conversation_sharing.py", "none", "no visibility toggle in the chat UI", "none", "LOW", "add toggle"),
"8.1.17": (PI, "MEDIUM", "backend api/services/suggested_questions.py (tests/test_suggested_questions.py); the chat UI shows a STATIC STARTER_QUESTIONS list in chat/page.tsx:98 (SuggestedQuestions.tsx " + ORPH + ")", "tests/test_suggested_questions.py (backend)", "none", "UI does not call the backend suggestions", "none", "LOW", "wire dynamic suggestions"),
"8.1.18": (PI, "MEDIUM", "backend follow-up questions (models/follow_up_question.py); FollowUpQuestions.tsx " + ORPH, "tests/test_suggested_questions.py (backend)", "none", "no follow-up questions displayed after answers", "none", "LOW", "wire FollowUpQuestions"),
"8.1.19": (VC, "HIGH", "6 locales (locales/ar, de, en, es, fr, pt), frontend/lib/i18n, LanguageMenu in dashboard/AppShell.tsx and site header; api/services/i18n.py", "tests/test_i18n.py", "none", "profile page note mentions a 2-language backend scope; coverage of every string across 6 languages is not proven", "none", "LOW", "run a missing-key check per locale"),
"8.2.1": (BE, "MEDIUM", VOICE, "tests/test_voice.py, tests/test_voice_providers.py (mocked)", "tenant isolation for Twilio fixed (0135)", "no real STT call", "Whisper/Deepgram key", "MEDIUM", "live smoke test with a funded key"),
"8.2.2": (BE, "MEDIUM", VOICE, "tests/test_voice.py, tests/test_voice_providers.py (mocked)", "none", "no real TTS call", "ElevenLabs/Google key", "MEDIUM", "live smoke test"),
"8.2.3": (IU, "MEDIUM", "VoiceOutput.tsx used by MessageBubble.tsx; streaming TTS in voice.py", "tests/test_voice.py", "none", "real-time streaming playback not exercised", "TTS provider", "LOW", "manual test"),
"8.2.4": (VC, "MEDIUM", "PushToTalkButton used by ChatComposer.tsx and voice-demo page", "frontend tests partial", "none", "browser microphone behaviour not run", "none", "LOW", "manual test"),
"8.2.5": (IU, "MEDIUM", "VADIndicator on voice-demo page; VAD logic in VoiceInput.tsx", "frontend tests partial", "none", "only on the demo page; real VAD accuracy not tested", "none", "LOW", "manual test"),
"8.2.6": (IU, "MEDIUM", "VoiceLanguageSelector used by voice-demo and VoiceSettings.tsx", "tests/test_voice_messages_and_settings.py", "none", "VoiceSettings.tsx " + ORPH, "STT/TTS providers", "LOW", "wire VoiceSettings"),
"8.2.7": (PI, "MEDIUM", "api/routers/voice_messages.py, api/services/voice_messages.py; VoiceMessageList.tsx " + ORPH, "tests/test_voice_messages_and_settings.py", "none", "no audio history screen", "none", "LOW", "wire VoiceMessageList"),
"8.2.8": (PI, "MEDIUM", "api/routers/voice_settings.py; VoiceSettings.tsx " + ORPH, "tests/test_voice_messages_and_settings.py", "none", "no voice settings screen", "none", "LOW", "wire VoiceSettings"),
"8.2.9": (PI, "MEDIUM", "VoiceSelector.tsx (used only by VoiceSettings.tsx which is unused); ElevenLabs voices in voice.py", "tests/test_voice_providers.py", "none", "no reachable voice selection screen", "ElevenLabs key", "LOW", "wire VoiceSettings"),
"8.2.10": (VC, "MEDIUM", "MicrophoneTest used by voice-demo page", "frontend tests partial", "none", "only reachable on /voice-demo", "none", "LOW", "link from settings"),
"8.2.11": (PI, "MEDIUM", "AudioPermission.tsx " + ORPH, "none located", "none", "permission handling only inside individual voice components", "none", "LOW", "wire AudioPermission"),
"8.2.12": (VC, "MEDIUM", "VoiceError used by VoiceInput, VoiceOutput, MicrophoneTest and voice-demo", "frontend tests partial", "none", "none found", "none", "INFO", "none"),
"8.2.13": (BE, "MEDIUM", "api/routers/twilio.py, api/services/telephony.py, twilio_sms.py; Telephony.tsx has only a test, no page imports it; dashboard/voice-agent page", "tests/test_telephony.py, tests/test_p0_twilio_tenant_isolation.py, tests/test_voice_agent.py", "tenant isolation fixed in P0 (migration 0135)", "no real call or SMS; Telephony.tsx unused", "Twilio account", "MEDIUM", "Twilio test credentials; wire UI"),
}
