# Part 14 - Documentation and deliverables. Facts read: README.md, ARCHITECTURE.md, docs/ with guides (ADMIN_GUIDE, FAQ, USER_GUIDE, WHITE_LABEL_GUIDE), docs/api (openapi.json, redoc, swagger), docs/admin, docs/developer,
# docs/deployment (RENDER.md, WORKER.md ...), docs/commercial (PRICING, PITCH ...), docs/user, docs/install, docs/faq, docs/diagrams; NO .pdf or .mp4 file found in the repo (find, depth 4, outside node_modules);
# landing page components frontend/components/figma/LandingSections.tsx and frontend/components/landing/*; agents.md contradicts the code (audit R-07).
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
NOPDF = "no PDF file exists in the repository"
V = {
"14.1.1": (VC, "HIGH", "README.md", "n/a", "n/a", "accuracy of every statement not re-read", "none", "INFO", "none"),
"14.1.2": (PI, "MEDIUM", "ARCHITECTURE.md, docs/architecture/OVERVIEW.md, DATA_FLOW.md, docs/diagrams/", "tests/docs partial", "n/a", "docs/architecture/LEGACY.md and agents.md describe obsolete or nonexistent routes (audit R-07)", "none", "LOW", "reconcile documentation with code"),
"14.1.3": (VC, "MEDIUM", "docs/install/, docs/AUTH_BACKEND_SETUP.md, install.sh", "n/a", "n/a", "not executed on a clean machine", "none", "LOW", "run the guide on a clean machine"),
"14.1.4": (VC, "HIGH", "docs/api/*.md and docs/api/openapi.json; FastAPI /docs", "tests/docs/test_api_reference.py", "n/a", "none found", "none", "INFO", "none"),
"14.1.5": (VC, "MEDIUM", "docs/DEPLOYMENT_GUIDE.md, docs/deployment/RENDER.md, WORKER.md, docs/developer/DEPLOYMENT.md", "tests/test_deployment.py", "n/a", "render.yaml and the worker doc may not match what actually runs on Render", "none", "MEDIUM", "align with reality"),
"14.1.6": (VC, "MEDIUM", "SECURITY.md, docs/SECURITY_REPORT.md, docs/architecture/SECURITY.md", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.1.7": (VC, "HIGH", "docs/guides/ADMIN_GUIDE.md and docs/admin/*", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.1.8": (VC, "HIGH", "docs/guides/USER_GUIDE.md and docs/user/*", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.1.9": (VC, "HIGH", "docs/guides/WHITE_LABEL_GUIDE.md, docs/admin/WHITE_LABEL.md", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.1.10": (VC, "MEDIUM", "docs/developer/* (CUSTOM_TOOLS, PLUGINS, WORKFLOWS, INTEGRATIONS)", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.1.11": (PI, "LOW", "troubleshooting content found only inside docs/api/ERRORS.md, WEBHOOKS.md and audit docs; no dedicated troubleshooting guide located", "n/a", "n/a", "dedicated guide not found", "none", "LOW", "write TROUBLESHOOTING.md"),
"14.1.12": (VC, "MEDIUM", "docs/guides/FAQ.md and docs/faq/", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.2.1": (NI, "HIGH", NOPDF + " (searched for *.pdf to depth 4)", "none", "n/a", "no architecture PDF; Markdown source exists", "none", "LOW", "export from Markdown"),
"14.2.2": (NI, "HIGH", NOPDF, "none", "n/a", "no feature-list PDF", "none", "LOW", "export from the verified feature CSV"),
"14.2.3": (NI, "HIGH", NOPDF, "none", "n/a", "no deployment PDF", "none", "LOW", "export from docs"),
"14.2.4": (NI, "HIGH", NOPDF, "none", "n/a", "no API PDF", "none", "LOW", "export from docs"),
"14.2.5": (NI, "HIGH", NOPDF + " (reports are Markdown: docs/SECURITY_REPORT.md, audit-reports/)", "none", "n/a", "no security-audit PDF", "none", "LOW", "export"),
"14.2.6": (NI, "HIGH", NOPDF + " (docs/PERFORMANCE_REPORT.md exists as Markdown)", "none", "n/a", "no benchmark PDF; no real benchmark data (audit R-06)", "none", "LOW", "run benchmarks first"),
"14.2.7": (NI, "HIGH", "no video file found in the repository (searched *.mp4)", "none", "n/a", "no demo video", "none", "LOW", "record a demo"),
"14.2.8": (VC, "MEDIUM", "docs/install/ and docs/developer/OVERVIEW.md", "n/a", "n/a", "none found", "none", "INFO", "none"),
"14.3.1": (VC, "MEDIUM", "frontend/components/figma/HeroStage.tsx, landing/LandingHero.tsx; home page frontend/app/page.tsx", "frontend tests partial", "n/a", "none found", "none", "INFO", "none"),
"14.3.2": (PI, "LOW", "voice-demo page exists; no video or interactive product demo section confirmed on the landing page", "none", "n/a", "no landing demo confirmed", "none", "LOW", "add demo"),
"14.3.3": (VC, "MEDIUM", "frontend/components/figma/LandingSections.tsx, landing/LandingBento.tsx", "frontend tests partial", "n/a", "none found", "none", "INFO", "none"),
"14.3.4": (PI, "LOW", "architecture schema on the landing page not confirmed", "none", "n/a", "not confirmed", "none", "LOW", "confirm"),
"14.3.5": (VC, "MEDIUM", "landing/LandingLogos.tsx and integrations section", "none", "n/a", "logos only; integration status not verified", "none", "LOW", "none"),
"14.3.6": (PI, "MEDIUM", "pricing content in docs/commercial/PRICING.md and billing page; landing pricing section not confirmed", "none", "n/a", "plan catalogue in production unverified (12.2.x)", "none", "LOW", "confirm"),
"14.3.7": (PI, "LOW", "security/compliance content in docs; landing section not confirmed", "none", "n/a", "not confirmed", "none", "LOW", "confirm"),
"14.3.8": (PI, "LOW", "docs site structure docs/index.md, _sidebar.md (docsify); link from landing page not confirmed", "none", "n/a", "not confirmed", "none", "LOW", "confirm"),
"14.3.9": (PI, "LOW", "FAQ exists in docs; landing FAQ section not confirmed", "none", "n/a", "not confirmed", "none", "LOW", "confirm"),
"14.4.1": (AM, "MEDIUM", "product naming is inconsistent: 'KnowFlow AI' appears in docs (COMPETITIVE_AUDIT_KNOWFLOW.md) while the repository is rag-saas-platform; final name not established", "none", "n/a", "no decided brand name found", "none", "LOW", "owner decision"),
"14.4.2": (PI, "LOW", "logo assets in frontend/public and figma components not enumerated here", "none", "n/a", "not verified", "none", "LOW", "confirm"),
"14.4.3": (VC, "MEDIUM", "colour tokens in the Tailwind/CSS theme and figma components", "none", "n/a", "none found", "none", "INFO", "none"),
"14.4.4": (PI, "LOW", "design guidelines: docs/commercial/BRANDING_OPTIONS.md; a formal brand charter document not located", "none", "n/a", "not located", "none", "LOW", "write a short brand guide"),
}
