# Part 3 - RAG pipeline. Facts read: chunking strategies ARE wired (api/security/documents.py ~3293-3351 uses resolve_chunking_strategy / chunk_content / chunk_parent_child),
# retrieval entry points in api/services/retrieval_pipeline.py (vector_search 388, bm25_search 628, reciprocal_rank_fusion 697, hybrid_search 710, hybrid_reranked_search 764),
# pgvector used when PGVECTOR_ENABLED (default True) on PostgreSQL, else numpy fallback.
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
ING = "called from the ingestion path in api/security/documents.py"
CH = "dispatched by api/services/chunk_config.py::chunk_content and wired in api/security/documents.py (~3293-3351)"
RET = "api/services/retrieval_pipeline.py"
SECR = "retrieval is organization-scoped through fetch_organization_chunks (tenant filter in application code; no database-level barrier, audit R-01)"
V = {
"3.1.1": (VC, "MEDIUM", "api/services/text_cleaning.py, " + ING, "tests/test_text_cleaning.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.2": (VC, "MEDIUM", "api/services/text_normalization.py (also used by query_rewriting.py), " + ING, "tests/test_text_normalization.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.3": (VC, "MEDIUM", "api/services/document_extraction.py + per-format extractors (see Part 2)", "per-format tests (test_pdf_extraction.py, test_docx_extraction.py, ...)", "see Part 2", "none found", "none", "INFO", "none"),
"3.1.4": (VC, "MEDIUM", "api/services/table_transformation.py, structure_detection.py; " + ING, "tests/test_table_transformation.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.5": (PI, "MEDIUM", "api/services/image_extraction.py, models/document_image.py, GET /documents/{id}/images (documents.py:589)", "tests/test_image_extraction.py", "see Part 2", "spec says extract captions and descriptions; image description by a vision model was not found in image_extraction.py (not fully read)", "vision model if required", "LOW", "confirm whether descriptions are generated"),
"3.1.6": (IU, "MEDIUM", "api/services/ocr.py (pytesseract/pdf2image), used by pdf and image extraction", "tests/test_ocr.py (needs Tesseract/poppler; installed in CI only)", "no security surface", "cannot run on this machine without the binaries", "Tesseract, poppler", "LOW", "run the OCR test in CI"),
"3.1.7": (VC, "MEDIUM", "api/services/language_detection.py, used in ingestion and sentence_chunking", "tests/test_language_detection.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.8": (VC, "MEDIUM", "api/services/structure_detection.py", "tests/test_structure_detection.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.9": (VC, "MEDIUM", "api/services/headings_extraction.py", "tests/test_headings_extraction.py", "no security surface", "none found", "none", "INFO", "none"),
"3.1.10": (VC, "MEDIUM", "api/services/metadata_enrichment.py, models/metadata_enrichment.py, GET /documents/{id}/metadata", "tests/test_metadata_enrichment.py, tests/test_metadata_normalization.py", "org-scoped", "none found", "none", "INFO", "none"),
"3.2.1": (VC, "HIGH", "token sliding-window chunk_text (api/security/documents.py:385), strategy 'fixed' (default)", "tests/test_chunking.py, tests/test_chunking_strategy_wiring.py", "none", "none found", "none", "INFO", "none"),
"3.2.2": (VC, "MEDIUM", "strategy 'recursive': " + CH + "; api/services/chunking.py", "tests/test_chunking.py, tests/test_chunking_strategy_wiring.py", "none", "none found", "none", "INFO", "none"),
"3.2.3": (VC, "MEDIUM", "strategy 'semantic': api/services/semantic_chunking.py; " + CH, "tests/test_semantic_chunking.py, tests/test_chunking_strategy_wiring.py", "none", "needs an embedding model at ingestion (cost/latency not measured)", "embedding model", "LOW", "measure ingestion cost"),
"3.2.4": (VC, "MEDIUM", "strategy 'markdown': api/services/markdown_chunking.py; " + CH, "tests/test_markdown_chunking.py", "none", "none found", "none", "INFO", "none"),
"3.2.5": (VC, "MEDIUM", "strategy 'code': api/services/code_chunking.py (no tree-sitter, deviation documented in the old doc); " + CH, "tests/test_code_chunking.py", "none", "structure awareness is heuristic, not parser-based", "none", "LOW", "none"),
"3.2.6": (VC, "MEDIUM", "strategy 'sentence': api/services/sentence_chunking.py; " + CH, "tests/test_sentence_chunking.py", "none", "none found", "none", "INFO", "none"),
"3.2.7": (VC, "MEDIUM", "strategy 'paragraph': api/services/paragraph_chunking.py; " + CH, "tests/test_paragraph_chunking.py", "none", "none found", "none", "INFO", "none"),
"3.2.8": (VC, "MEDIUM", "strategy 'parent_child': api/services/parent_child_chunking.py, chunk_parent_child called from api/security/documents.py", "tests/test_parent_child_chunking.py, tests/test_parent_child_chunking_wiring.py", "none", "retrieval of the parent from a child hit not re-read", "none", "LOW", "confirm parent expansion at query time"),
"3.3.1": (VC, "HIGH", "resolve_chunk_size in api/services/chunk_config.py, org setting chunk_size (api/schemas/organization_settings.py)", "tests/test_chunk_config.py, tests/test_organization_settings.py", "bounded by CHUNK_SIZE_MAX_TOKENS", "none found", "none", "INFO", "none"),
"3.3.2": (VC, "HIGH", "resolve_chunk_overlap in chunk_config.py (must be smaller than size)", "tests/test_chunk_config.py", "validated", "none found", "none", "INFO", "none"),
"3.3.3": (VC, "MEDIUM", "api/services/embedding_config.py per-organization embedding model; dimension safety", "tests/test_embedding_config.py, tests/test_embedding_dimension_safety.py", "none", "changing model requires re-embedding (staleness route exists)", "none", "LOW", "none"),
"3.3.4": (VC, "HIGH", "resolve strategy in api/services/retrieval_config.py (hybrid, vector, bm25)", "tests/test_retrieval_config.py, tests/test_retrieval_pipeline.py", "none", "none found", "none", "INFO", "none"),
"3.3.5": (VC, "MEDIUM", "resolve_reranker_model / resolve_reranker_top_k in retrieval_config.py; _get_reranker in " + RET, "tests/test_retrieval_config.py", "none", "model download at first use (memory on 512 MB host)", "model download", "LOW", "measure memory"),
"3.3.6": (VC, "HIGH", "top_k in retrieval_config.py, bound in api/routers/search.py", "tests/test_retrieval_config.py", "bounded", "none found", "none", "INFO", "none"),
"3.3.7": (VC, "MEDIUM", "resolve_score_threshold in retrieval_config.py (retrieval_config.py:141)", "tests/test_retrieval_config.py", "none", "none found", "none", "INFO", "none"),
"3.4.1": (VC, "HIGH", "bm25_search with rank_bm25 BM25Okapi and per-organization index cache (" + RET + ":628)", "tests/test_bm25_index_cache.py, tests/test_retrieval_pipeline.py", SECR, "whole-organization chunk loading into memory (audit risk)", "none", "MEDIUM", "benchmark large organizations"),
"3.4.2": (IU, "MEDIUM", "vector_search (" + RET + ":388): pgvector ranking when PGVECTOR_ENABLED on PostgreSQL, else in-memory numpy cosine", "tests/test_retrieval_pipeline.py and tests/test_pgvector_iterative_scan.py (SQLite / mocked; the pgvector SQL path is not proven by a real PostgreSQL run in CI)", SECR, "which branch production takes is unproven", "PostgreSQL + pgvector", "MEDIUM", "PostgreSQL integration test in CI (audit P1-4)"),
"3.4.3": (VC, "HIGH", "reciprocal_rank_fusion (" + RET + ":697), hybrid_search (:710)", "tests/test_retrieval_pipeline.py", "none", "none found", "none", "INFO", "none"),
"3.4.4": (IU, "MEDIUM", "hybrid_reranked_search (" + RET + ":764) with a cross-encoder from sentence-transformers", "tests/test_retrieval_pipeline.py (model mocked)", "none", "real model load/latency/memory not measured", "model download", "MEDIUM", "measure on the real host"),
"3.4.5": (PI, "MEDIUM", "only abbreviation expansion in api/services/query_rewriting.py (_ABBREVIATION_EXPANSIONS, expand_abbreviations); no synonym expansion found in query_rewriting.py, multi_query.py or retrieval_config.py", "tests/test_query_rewriting.py", "none", "spec says synonyms; none implemented", "none", "LOW", "implement synonym or LLM expansion or amend the spec"),
"3.4.6": (VC, "MEDIUM", "api/services/query_rewriting.py wired in " + RET, "tests/test_query_rewriting.py", "none", "none found", "none", "INFO", "none"),
"3.4.7": (IU, "MEDIUM", "api/services/hyde.py wired in " + RET + " and retrieval_config.py", "tests/test_hyde.py (LLM mocked)", "none", "quality benefit never measured", "LLM provider", "LOW", "evaluate with Eval Lab"),
"3.4.8": (IU, "MEDIUM", "api/services/multi_query.py wired in " + RET, "tests/test_multi_query.py (LLM mocked)", "none", "quality benefit never measured", "LLM provider", "LOW", "evaluate with Eval Lab"),
"3.4.9": (VC, "MEDIUM", "api/services/metadata_filtering.py used by " + RET + ", api/schemas/search.py, tools/search_kb.py", "tests/test_metadata_filtering.py", SECR, "none found", "none", "INFO", "none"),
"3.4.10": (VC, "MEDIUM", "api/services/semantic_filtering.py used by " + RET, "tests/test_semantic_filtering.py", "none", "none found", "none", "INFO", "none"),
"3.4.11": (VC, "MEDIUM", "resolve_rrf_k and source weights in retrieval_config.py", "tests/test_retrieval_config.py", "none", "none found", "none", "INFO", "none"),
"3.4.12": (VC, "MEDIUM", "resolve_reranker_model in retrieval_config.py", "tests/test_retrieval_config.py", "none", "none found", "none", "INFO", "none"),
"3.4.13": (VC, "HIGH", "top_k configurable via org settings and search request (same mechanism as 3.3.6; the original text lists it twice)", "tests/test_retrieval_config.py", "bounded", "duplicate of 3.3.6 in the spec", "none", "INFO", "none"),
"3.4.14": (VC, "MEDIUM", "api/services/context_compression.py used by api/services/generation.py", "tests/test_context_compression.py", "none", "none found", "none", "INFO", "none"),
"3.4.15": (VC, "MEDIUM", "api/services/duplicate_removal.py (also used by multi_query)", "tests/test_duplicate_removal.py", "none", "none found", "none", "INFO", "none"),
"3.4.16": (VC, "MEDIUM", "select_diverse_chunks / MMR in api/services/mmr.py wired in " + RET + " (~930-950)", "tests/test_mmr.py", "none", "none found", "none", "INFO", "none"),
}
