# Part 13 - Developer experience. Facts read: pyproject.toml has [tool.pytest], [tool.coverage], [tool.ruff] (no [tool.black], no [tool.mypy]); .pre-commit-config.yaml runs ruff, ruff-format and detect-secrets;
# .github/dependabot.yml exists; CI = .github/workflows/ci.yml (docker build jobs build-backend/build-frontend, backend-tests, backend-security, frontend-checks), bandit.yml (non-blocking), celery-worker.yml (scheduled burst);
# .circleci/config.yml with --cov-fail-under=75; no Railway/Fly/AWS/GCP/Azure/DigitalOcean/Kubernetes/Helm/Terraform assets found (find for *.tf, Chart.yaml, fly.toml, railway.*).
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
CI = ".github/workflows/ci.yml, .circleci/config.yml"
V = {
"13.1.1": (PI, "MEDIUM", "type hints are widely used (FastAPI/Pydantic signatures) but not enforced everywhere; no type checker configured", "none", "n/a", "'everywhere' is not enforced or measured", "none", "LOW", "measure with mypy/pyright"),
"13.1.2": (VC, "HIGH", "[tool.ruff.lint] in pyproject.toml; ruff in pre-commit; 'ruff check api' passes (Copilot audit and earlier run: All checks passed)", "CI lint step", "n/a", "none found", "none", "INFO", "none"),
"13.1.3": (PI, "HIGH", "ruff-format is used instead of Black (.pre-commit-config.yaml); no [tool.black]", "pre-commit", "n/a", "Black itself is not configured: a functionally equivalent formatter is used", "none", "INFO", "accept ruff-format as the formatter"),
"13.1.4": (NI, "MEDIUM", "none: no [tool.mypy] and no mypy hook or CI job found", "none", "n/a", "no static type checking for Python", "none", "LOW", "add mypy or pyright"),
"13.1.5": (VC, "HIGH", "pytest configured in pyproject.toml; about 6,130 tests discovered (Copilot audit)", "CI backend-tests and CircleCI api-tests green on main", "n/a", "tests mostly on SQLite", "none", "INFO", "none"),
"13.1.6": (PI, "HIGH", "coverage configured ([tool.coverage.run]); CircleCI gate is --cov-fail-under=75; measured 77.41% (Copilot audit)", "CircleCI api-tests", "n/a", "spec asks for more than 90%; measured about 77% on the CircleCI test subset", "none", "MEDIUM", "raise coverage or revise the target"),
"13.1.7": (VC, "HIGH", ".pre-commit-config.yaml: ruff, ruff-format, detect-secrets", "n/a", "secret detection hook", "hook installation is per developer", "none", "INFO", "none"),
"13.1.8": (VC, "HIGH", ".github/dependabot.yml; open Dependabot PRs exist (e.g. stripe 16)", "n/a", "n/a", "none found", "none", "INFO", "none"),
"13.1.9": (VC, "MEDIUM", "bandit workflow (non-blocking), backend-security job, Snyk check, pip-audit", "CI backend-security success", "n/a", "bandit reports 11 medium findings and is non-blocking", "none", "MEDIUM", "triage bandit findings"),
"13.2.1": (VC, "HIGH", "tests/ unit tests", "pytest suite", "n/a", "none found", "none", "INFO", "none"),
"13.2.2": (VC, "MEDIUM", "*_integration.py tests (mocked providers) listed in .circleci/config.yml", "CircleCI api-tests", "n/a", "most 'integration' tests use mocks and SQLite", "none", "LOW", "add real-service integration"),
"13.2.3": (VC, "HIGH", "route-level tests using httpx AsyncClient (tests/test_auth_api.py etc.)", "pytest suite", "n/a", "183 of 943 operations have no test referencing their path (Copilot heuristic)", "none", "MEDIUM", "cover the untested routes"),
"13.2.4": (PI, "MEDIUM", "tests/test_e2e_lifecycle.py (backend lifecycle); no browser E2E (no Playwright/Cypress config found in frontend)", "tests/test_e2e_lifecycle.py", "n/a", "no browser-driven end-to-end test", "none", "MEDIUM", "add Playwright smoke tests"),
"13.2.5": (VC, "HIGH", "security tests: test_p0_*, test_ssrf_hardening.py, test_audit_tenant_isolation.py, test_mcp_builtin_tools_security.py", "pytest suite", "n/a", "no RLS test on PostgreSQL in CI", "none", "MEDIUM", "audit P1-4"),
"13.2.6": (VC, "MEDIUM", "each P0/P1/P2 fix has a dedicated regression test; rag-pipeline-regression job in CircleCI", "CircleCI rag-pipeline-regression success", "n/a", "none found", "none", "INFO", "none"),
"13.2.7": (PI, "MEDIUM", "LLM behaviour tests use mocks (tests/test_llm_providers.py); live tests (billing/LLM) are skipped without keys", "skipped live tests", "n/a", "no test with a real LLM runs in CI", "LLM key", "MEDIUM", "scheduled live smoke job"),
"13.2.8": (PI, "MEDIUM", "RAG pipeline tests and rag-pipeline-regression job; Eval Lab exists", "tests/test_retrieval_pipeline.py", "n/a", "no quality baseline on real data (audit R-06)", "dataset", "MEDIUM", "SQuAD run"),
"13.2.9": (VC, "MEDIUM", "tests/test_agent_*.py", "pytest suite", "n/a", "LLM mocked", "none", "LOW", "none"),
"13.2.10": (PI, "MEDIUM", "PostgreSQL concurrency tests exist (test_postgres_*.py) but are opt-in and not in CI", "tests/test_postgres_integration.py", "n/a", "database behaviour proven on SQLite in CI only", "PostgreSQL service", "HIGH", "audit P1-4"),
"13.2.11": (PI, "MEDIUM", "tests/test_deployment.py; docker build jobs in CI", "tests/test_deployment.py; CI build-backend/build-frontend", "n/a", "no post-deploy smoke test against a running service", "deployed service", "LOW", "add post-deploy health check"),
"13.3.1": (VC, "HIGH", "ruff and eslint in CI (frontend-checks)", CI, "n/a", "none found", "none", "INFO", "none"),
"13.3.2": (PI, "MEDIUM", "tsc --noEmit for the frontend; no Python type checking (see 13.1.4)", "CI frontend-checks", "n/a", "Python type check missing", "none", "LOW", "see 13.1.4"),
"13.3.3": (VC, "HIGH", "backend-tests job", "CI success on main", "n/a", "job takes about 60 minutes (limit 75)", "none", "MEDIUM", "split or speed up tests"),
"13.3.4": (VC, "MEDIUM", "integration tests inside backend-tests and CircleCI api-tests", "CI success on main", "n/a", "mocked providers", "none", "LOW", "none"),
"13.3.5": (VC, "HIGH", "backend-security, bandit, Snyk", "CI success on main", "n/a", "bandit non-blocking", "none", "LOW", "none"),
"13.3.6": (VC, "HIGH", "docker/build-push-action jobs build-backend and build-frontend", "CI success on main", "n/a", "none found", "none", "INFO", "none"),
"13.3.7": (NI, "MEDIUM", "none: no browser E2E job in CI (see 13.2.4)", "none", "n/a", "absent", "none", "MEDIUM", "add Playwright job"),
"13.3.8": (PI, "MEDIUM", "Render/Vercel redeploy from git pushes (platform-managed); no CI deploy job; migrations not applied automatically (audit R-03)", "n/a", "n/a", "no automated migration step; deployment is not a pipeline stage", "Render/Vercel", "HIGH", "add a controlled migration step"),
"13.4.1": (VC, "HIGH", "Dockerfile, Dockerfile.api, Dockerfile.plugin-sandbox", "CI docker builds", "n/a", "none found", "none", "INFO", "none"),
"13.4.2": (VC, "MEDIUM", "docker-compose.yml, docker-compose.selfhosted.yml, docker-compose.observability.yml", "none", "n/a", "compose stacks not run in this audit", "Docker host", "LOW", "test a clean up"),
"13.4.3": (PI, "HIGH", "production API runs on Render (docs/deployment/RENDER.md) but render.yaml describes only the old Streamlit prototype (audit R-07); gunicorn only, no worker (audit R-02)", "none", "n/a", "blueprint out of date", "Render", "MEDIUM", "update render.yaml"),
"13.4.4": (NI, "MEDIUM", "none: no Railway file found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.5": (NI, "MEDIUM", "none: no fly.toml found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.6": (NI, "MEDIUM", "none: no AWS-specific deployment assets found", "none", "n/a", "absent (generic Docker only)", "none", "LOW", "document or drop"),
"13.4.7": (NI, "MEDIUM", "none: no GCP-specific assets found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.8": (NI, "MEDIUM", "none: no Azure-specific assets found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.9": (NI, "MEDIUM", "none: no DigitalOcean assets found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.10": (NI, "MEDIUM", "none: no Kubernetes manifests found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.11": (NI, "MEDIUM", "none: no Chart.yaml found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.4.12": (NI, "MEDIUM", "none: no .tf files found", "none", "n/a", "absent", "none", "LOW", "document or drop"),
"13.5.1": (VC, "MEDIUM", "see 10.3.2", "tests/test_tracing.py", "n/a", "duplicate of 10.3.2 in the spec", "log backend", "INFO", "none"),
"13.5.2": (VC, "MEDIUM", "see 10.3.3", "tests/test_tracing.py", "n/a", "duplicate of 10.3.3", "none", "INFO", "none"),
"13.5.3": (VC, "MEDIUM", "see 10.3.4", "tests/test_tracing.py", "n/a", "duplicate of 10.3.4", "none", "INFO", "none"),
"13.5.4": (BE, "MEDIUM", "see 10.3.5", "tests/test_tracing.py", "n/a", "no collector", "OTel collector", "LOW", "optional"),
"13.5.5": (BE, "MEDIUM", "see 10.3.6", "tests/test_agent_traces.py", "n/a", "Datadog not configured", "Datadog", "LOW", "optional"),
"13.5.6": (VC, "MEDIUM", "see 10.3.7", "tests/test_retrieval_diagnostics.py", "n/a", "duplicate of 10.3.7", "none", "INFO", "none"),
"13.5.7": (VC, "MEDIUM", "see 10.3.8", "tests/test_agent_traces.py", "n/a", "duplicate of 10.3.8", "none", "INFO", "none"),
"13.5.8": (BE, "MEDIUM", "see 10.3.9", "tests/test_error_tracking.py", "n/a", "Sentry DSN unverified", "Sentry", "LOW", "verify DSN"),
"13.5.9": (VC, "MEDIUM", "see 10.3.10", "tests/test_latency_metrics.py", "n/a", "see /metrics exposure", "none", "MEDIUM", "set METRICS_AUTH_TOKEN"),
"13.5.10": (VC, "MEDIUM", "see 10.3.11", "tests/test_cost_tracking.py", "n/a", "duplicate of 10.3.11", "none", "INFO", "none"),
"13.5.11": (VC, "MEDIUM", "see 10.3.12", "tests/test_token_usage.py", "n/a", "duplicate of 10.3.12", "none", "INFO", "none"),
"13.5.12": (PI, "MEDIUM", "request id + trace id + agent traces + flight recorder exist separately; one end-to-end view of a request across HTTP, retrieval, LLM and tools was not located", "tests/test_tracing.py, tests/test_agent_traces.py", "n/a", "no single trace view joining all stages", "none", "LOW", "add a request trace view"),
}
