# Part 9 - Public API and integrations. Facts read: api/routers/public_api.py defines /v1/chat (279), /v1/documents (303), /v1/knowledge-bases (321), /v1/conversations (336), /v1/search (347),
# /v1/agents/run (357), /v1/usage (373), /v1/analytics (384), /v1/embed (396), plus key management (rotate 157, schedule-rotation 183, rate-limit 214, quota 235). sdks/ holds python, js, react, vue packages with tests.
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
PA = "api/routers/public_api.py"
KT = "tests/test_public_api.py"
KEYSEC = "API-key authentication (api/security/public_api_auth.py) with scopes"
V = {
"9.1.1": (VC, "MEDIUM", "POST /v1/chat (" + PA + ":279), SSE capable", KT, KEYSEC, "real LLM answer not exercised", "LLM provider", "LOW", "smoke test"),
"9.1.2": (VC, "MEDIUM", "POST /v1/documents (" + PA + ":303)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.1.3": (VC, "MEDIUM", "POST /v1/knowledge-bases (" + PA + ":321)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.1.4": (VC, "MEDIUM", "GET /v1/conversations (" + PA + ":336)", KT, KEYSEC + "; conversation isolation fixed in P0", "none found", "none", "INFO", "none"),
"9.1.5": (VC, "MEDIUM", "POST /v1/search (" + PA + ":347)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.1.6": (VC, "MEDIUM", "POST /v1/agents/run (" + PA + ":357)", KT, KEYSEC, "agent run needs an LLM for a real result", "LLM provider", "LOW", "smoke test"),
"9.1.7": (VC, "MEDIUM", "GET /v1/usage (" + PA + ":373)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.1.8": (VC, "MEDIUM", "GET /v1/analytics (" + PA + ":384)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.1.9": (VC, "MEDIUM", "POST /v1/embed (" + PA + ":396)", KT, KEYSEC, "none found", "none", "INFO", "none"),
"9.2.1": (VC, "HIGH", "key create/list/get routes (" + PA + ":62-136), api/services/organization_api_keys.py; UI dashboard/settings/api-keys", "tests/test_api_key_management.py, tests/test_agent_api_keys.py", "keys shown once, stored hashed (to confirm in organization_api_keys.py)", "none found", "none", "INFO", "none"),
"9.2.2": (VC, "HIGH", "POST /api-keys/{id}/rotate, rotation-history, schedule-rotation (" + PA + ":157-183); api/tasks/api_key_maintenance.py", "tests/test_api_key_management.py", "none", "scheduled rotation needs Celery beat (audit R-02)", "Celery beat", "LOW", "stage test"),
"9.2.3": (VC, "MEDIUM", "expiry field and GET /organizations/{id}/api-keys/expiring (" + PA + ":125)", "tests/test_api_key_management.py", "expired keys rejected (to confirm in test)", "none found", "none", "LOW", "confirm expired-key rejection test"),
"9.2.4": (VC, "HIGH", "GET /api-keys/scopes (" + PA + ":117) and scope checks", "tests/test_api_key_management.py, tests/test_public_api.py", "scope enforcement", "none found", "none", "INFO", "none"),
"9.2.5": (VC, "MEDIUM", "GET /api-keys/{id}/rate-limit (" + PA + ":214); api/security/rate_limit.py", "tests/test_rate_limiting_integration.py, tests/test_rate_limit_degradation.py", "without Redis the limiter falls back to in-process memory (audit R-09)", "per-process only in production without Redis", "Redis", "MEDIUM", "provision Redis for production"),
"9.2.6": (VC, "MEDIUM", "GET /api-keys/{id}/quota (" + PA + ":235-253); api/security/quotas.py", "tests/test_quotas.py", "none", "none found", "none", "INFO", "none"),
"9.2.7": (VC, "MEDIUM", "api/routers/webhooks.py, api/services/webhooks.py, api/tasks/webhooks.py; UI dashboard/settings/webhooks", "tests/test_webhooks.py, tests/test_inbound_webhooks.py, tests/test_p2_bill015_webhook_robustness.py", "outbound webhook signing and SSRF guard to confirm", "delivery retries need Celery", "Celery worker", "MEDIUM", "stage test"),
"9.2.8": (VC, "MEDIUM", "api/routers/api_versioning.py, api/services/api_versioning.py", "tests/test_api_versioning.py", "none", "none found", "none", "INFO", "none"),
"9.2.9": (VC, "MEDIUM", "FastAPI generates /openapi.json and /docs; dashboard/api-docs page", "no dedicated test located", "docs exposure in production not checked", "docs endpoints may be public", "none", "LOW", "decide whether to hide docs in production"),
"9.2.10": (VC, "MEDIUM", "sdks/python/rag_saas_sdk with sdks/python/tests/test_client.py", "sdks/python/tests/test_client.py (not executed in this pass)", "none", "SDK tests not executed here; compatibility with the live API not proven", "none", "LOW", "run SDK tests in CI"),
"9.2.11": (VC, "MEDIUM", "sdks/js/src with sdks/js/tests/client.test.ts and endpoints.test.ts", "sdks/js/tests (not executed in this pass)", "none", "SDK tests not executed here", "none", "LOW", "run SDK tests in CI"),
"9.3.1": (VC, "MEDIUM", "api/routers/widget.py serves the embed script; api/services/widget.py", "tests/test_widget.py", "public-key auth (api/security/widget_auth.py) and domain allowlist", "none found", "none", "INFO", "none"),
"9.3.2": (VC, "MEDIUM", "widget config logo", "tests/test_widget.py, tests/test_widget_branding_fallback.py", "none", "none found", "none", "INFO", "none"),
"9.3.3": (VC, "MEDIUM", "widget config colour", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.4": (VC, "MEDIUM", "widget config name", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.5": (VC, "MEDIUM", "widget config avatar", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.6": (VC, "MEDIUM", "widget welcome message", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.7": (VC, "MEDIUM", "widget suggested questions (api/services/widget.py)", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.8": (VC, "MEDIUM", "widget position", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.9": (VC, "MEDIUM", "widget language", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.10": (VC, "MEDIUM", "widget theme", "tests/test_widget.py", "none", "none found", "none", "INFO", "none"),
"9.3.11": (VC, "MEDIUM", "sdks/react/src/RAGWidget.tsx with __tests__", "sdks/react/src/__tests__ (not executed in this pass)", "none", "tests not executed here", "none", "LOW", "run in CI"),
"9.3.12": (VC, "MEDIUM", "sdks/vue/src/RAGWidget.vue with __tests__", "sdks/vue/src/__tests__ (not executed in this pass)", "none", "tests not executed here", "none", "LOW", "run in CI"),
"9.3.13": (VC, "MEDIUM", "GET /widget/iframe in api/routers/widget.py:102 with allow-list", "tests/test_widget_domain_allowlist.py", "frame-ancestors allow-list", "none found", "none", "INFO", "none"),
"9.3.14": (VC, "MEDIUM", "sdks/js package (browser capable) and the embed script", "sdks/js/tests (not executed in this pass)", "none", "tests not executed here", "none", "LOW", "run in CI"),
"9.4.1": (BE, "MEDIUM", "api/routers/chat_integrations_slack.py, api/services/chat_integrations/", "tests/test_chat_integrations.py, tests/test_chat_integration_webhook_auth.py", "request signature verification (api/security/chat_integrations_signature.py)", "no real Slack workspace exercised", "Slack app", "MEDIUM", "sandbox workspace test"),
"9.4.2": (BE, "MEDIUM", "api/routers/chat_integrations_teams.py, api/security/teams_bot_auth.py", "tests/test_chat_integration_webhook_auth.py", "bot token verification (TEAMS_BOT_ID must be set in production)", "no real Teams tenant exercised", "Microsoft Bot registration", "MEDIUM", "sandbox test; set TEAMS_BOT_ID"),
"9.4.3": (BE, "MEDIUM", "api/routers/chat_integrations_discord.py", "tests/test_chat_integrations.py", "shared secret DISCORD_GATEWAY_SHARED_SECRET must be set in production", "no real Discord server exercised", "Discord application", "MEDIUM", "sandbox test; set secret"),
}
