# Part 12 - Billing. Facts read: Stripe and Paystack providers (api/services/billing_stripe.py, billing_paystack.py, billing_providers/), webhooks /billing/stripe/webhook and /billing/paystack/webhook
# (api/routers/billing.py:511,538), UI frontend/app/dashboard/billing/page.tsx (checkout, subscribe, cancel, reactivate, credits, invoices). Greps under api/: 'coupon' and 'flutterwave' return nothing;
# no per-plan voice-minutes limit found. NOTHING was ever run against a real provider (audit R-05); tests are synthetic; live tests are skipped.
VC, PI, NI, IU, BE, BR, AM = ("VERIFIED_COMPLETE", "PARTIALLY_IMPLEMENTED", "NOT_IMPLEMENTED", "IMPLEMENTED_UNVERIFIED",
                              "BLOCKED_EXTERNAL", "BROKEN", "AMBIGUOUS_REQUIREMENT")
NOLIVE = "never run against a real provider sandbox; live tests are skipped (audit R-05)"
V = {
"12.1.1": (PI, "HIGH", "checkout via Stripe and Paystack: api/services/billing_stripe.py, billing_paystack.py; UI POST /organizations/{id}/billing/checkout (billing/page.tsx:229); webhooks in billing.py:511,538", "tests/test_billing.py, tests/test_billing_stripe_events.py, tests/test_p1_bill003_005_006_stripe_chain.py (synthetic events)", "webhook signature verification, no free paid plans (P0 fix)", "Flutterwave named in the spec is absent; " + NOLIVE, "Stripe/Paystack test keys", "HIGH", "run sandbox end to end; decide on Flutterwave"),
"12.1.2": (IU, "HIGH", "subscription lifecycle in billing_stripe.py / billing_paystack.py / admin_subscriptions; UI subscribe/cancel/reactivate", "tests/test_billing.py, tests/test_postgres_subscription_concurrency.py (opt-in PostgreSQL, not in CI)", "row locks added", NOLIVE + "; recurring renewal events not observed", "Stripe/Paystack", "HIGH", "sandbox renewal scenario"),
"12.1.3": (VC, "MEDIUM", "invoice state machine and proof of payment: api/services/billing_invoices.py, tests for states", "tests/test_p1_bill002_invoice_state_machine.py, tests/test_p1_bill010_invoices.py, tests/test_p1_r2_invoice_proof_and_rules.py", "financial writes reserved to superadmin", "refunded state not handled (BILL-016); manual proof not verified against a bank", "none", "MEDIUM", "decide refund policy"),
"12.1.4": (NI, "HIGH", "none: grep 'coupon' under api/ returns nothing", "none", "n/a", "promo codes absent", "none", "MEDIUM", "implement or drop from the offer"),
"12.1.5": (PI, "MEDIUM", "'trial' appears in config and admin subscription/analytics code (api/config.py, services/admin_subscriptions.py, analytics.py)", "tests/test_admin_subscriptions.py", "none", "trial end behaviour (conversion/expiry) not verified; provider trial settings not exercised", "Stripe/Paystack", "MEDIUM", "verify trial lifecycle"),
"12.1.6": (IU, "MEDIUM", "plan change in subscription services; effective-plan logic (BILL-007)", "tests/test_p1_bill007_effective_plan.py", "no free paid plans", NOLIVE + "; proration not verified", "Stripe/Paystack", "MEDIUM", "sandbox upgrade"),
"12.1.7": (IU, "MEDIUM", "downgrade handling referenced in api/routers/billing.py and config", "tests/test_billing.py", "none", NOLIVE + "; effect on existing data over new limits not verified", "Stripe/Paystack", "MEDIUM", "sandbox downgrade and limit enforcement"),
"12.1.8": (IU, "HIGH", "POST /organizations/{id}/billing/cancel and reactivate (UI billing/page.tsx:285,301); admin cancel at provider", "tests/test_p1_bill006_admin_cancel_at_provider.py", "none", NOLIVE, "Stripe/Paystack", "MEDIUM", "sandbox cancellation"),
"12.1.9": (PI, "MEDIUM", "usage metering via api/services/billing_usage.py and credits spending; no metered-billing report to the provider found", "tests/test_billing_credits_spend_caps.py", "spend caps", "spend caps not atomic (BILL-012, unverified); usage is paid through credits, not invoiced after use", "none", "MEDIUM", "clarify requirement"),
"12.1.10": (IU, "HIGH", "credits: api/services/billing_credits.py, credit packs, preflight in orchestrator; UI credits on billing page", "tests/test_billing_credit_packs.py, tests/test_p2_bill011_020_credits.py, tests/test_postgres_credits_concurrency.py (not in CI)", "unpaid top-up flag CREDITS_ALLOW_UNPAID_TOPUP must be false in production (owner action)", "Paystack credit purchase not supported; currency inconsistency (BILL-018); " + NOLIVE, "Stripe/Paystack", "HIGH", "sandbox credit purchase; set the flag"),
"12.1.11": (VC, "MEDIUM", "GET /organizations/{id}/billing/invoices and payment history on the billing page", "tests/test_billing_idor.py, tests/test_p1_bill010_invoices.py", "org-scoped, IDOR test", "none found", "none", "INFO", "none"),
"12.2.1": (IU, "MEDIUM", "plans are rows in the plans table (models/admin.py Plan, GET /billing/plans); Free defined by data, BILLING_DEFAULT_PLAN='free'", "tests/test_billing.py", "none", "production plan rows and limits (3 documents, 10 questions/day) not verified; plan data is not in code", "production database", "MEDIUM", "read-only check of the plans table"),
"12.2.2": (IU, "MEDIUM", "plan row (data)", "tests/test_billing.py", "none", "production values unverified", "production database", "LOW", "read-only check"),
"12.2.3": (IU, "MEDIUM", "plan row (data)", "tests/test_billing.py", "none", "production values unverified", "production database", "LOW", "read-only check"),
"12.2.4": (IU, "LOW", "no 'business' plan in code; plans are data; the local preview seeded free/starter/pro/enterprise only", "none", "none", "a Business plan may not exist", "production database", "MEDIUM", "confirm plan catalogue"),
"12.2.5": (IU, "LOW", "Enterprise plan row (data); SSO exists (10.4.1); on-premise partial (10.4.10)", "none", "none", "on-premise not delivered as a product", "production database", "LOW", "confirm"),
"12.3.1": (IU, "HIGH", "AI credits (see 12.1.10)", "tests/test_p0_credits_no_free_response.py", "no free responses without credits (P0 fix)", NOLIVE, "Stripe/Paystack", "HIGH", "see 12.1.10"),
"12.3.2": (VC, "MEDIUM", "document quota enforcement (api/security/quotas.py, upload path)", "tests/test_quotas.py", "org-scoped", "plan-to-quota linkage in production not verified", "none", "LOW", "verify linkage"),
"12.3.3": (PI, "MEDIUM", "storage fields in models/organization_quota.py and schemas", "tests/test_quotas.py", "none", "enforcement on upload not confirmed", "none", "MEDIUM", "confirm and test enforcement"),
"12.3.4": (VC, "MEDIUM", "request quotas and rate limits (api/security/quotas.py, user_limits.py)", "tests/test_quotas.py, tests/test_user_limits.py", "none", "none found", "none", "LOW", "none"),
"12.3.5": (VC, "MEDIUM", "token quotas and usage tracking (api/services/token_usage.py, usage)", "tests/test_token_usage.py", "none", "none found", "none", "LOW", "none"),
"12.3.6": (NI, "MEDIUM", "none: no voice-minutes meter or limit found under api/", "none", "n/a", "voice usage is not metered per plan", "none", "LOW", "implement"),
"12.3.7": (VC, "MEDIUM", "usage view: GET /organizations/{id}/usage (+details/export), UI billing page", "tests/test_usage.py", "org-scoped", "none found", "none", "INFO", "none"),
}
