"""Generate static discovery/route/table inventories, without opening a database."""

from __future__ import annotations

import ast
import os
import re
from collections import Counter
from pathlib import Path

from sqlalchemy.engine import make_url

from scripts.staging_target import ROOT, isolated_environment

EXCLUDED = {
    ".git", ".claude", ".venv", ".venv-1", "venv", "node_modules", ".next",
    "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache", "staging-artifacts", ".tools",
}
MARKERS = re.compile(r"\b(TODO|FIXME|XXX|HACK|BUG|UNKNOWN|PARTIAL|TRACED|BLOCKED)\b")
EXTENSIONS = {".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".jsonc", ".md", ".mdx",
              ".yaml", ".yml", ".toml", ".ini", ".sh", ".txt", ".css", ".scss", ".vue", ".svg"}
GENERATED_OUTPUTS = {"docs/AUTONOMOUS_AUDIT_01_DISCOVERY.md", "docs/AUTONOMOUS_AUDIT_03_SECURITY.md"}


def source_files():
    for current, directories, names in os.walk(ROOT):
        directories[:] = sorted(name for name in directories if name not in EXCLUDED)
        for name in sorted(names):
            path = Path(current) / name
            if name.startswith(".env"):
                continue
            if path.relative_to(ROOT).as_posix() in GENERATED_OUTPUTS:
                continue
            yield path


def dependencies(dependant, seen=None):
    seen = set() if seen is None else seen
    names = set()
    for dependency in dependant.dependencies:
        if id(dependency) in seen:
            continue
        seen.add(id(dependency))
        if dependency.call:
            names.add(getattr(dependency.call, "__name__", type(dependency.call).__name__))
        names.update(dependencies(dependency, seen))
    return names


def generate() -> None:
    # Import API metadata only under isolated dummy settings; no engine.connect/lifespan.
    env = isolated_environment(make_url("postgresql+asyncpg://localtest:localtest@127.0.0.1:1/metadata_only"))
    os.environ.clear()
    os.environ.update(env)
    from fastapi.routing import APIRoute, iter_route_contexts

    from api.main import app
    from api.models import Base

    files = list(source_files())
    inventory, markers, parse_errors = [], [], []
    counts = Counter()
    test_functions = 0
    for path in files:
        relative = path.relative_to(ROOT).as_posix()
        counts[relative.split("/")[0]] += 1
        text_source = (
            path.suffix in EXTENSIONS
            or path.name.startswith("Dockerfile")
            or path.name in {".gitignore", ".dockerignore", "Makefile"}
        )
        if not text_source or path.name.endswith("-lock.json") or path.name == "uv.lock":
            inventory.append(f"| `{relative}` | UNKNOWN (metadata only, {path.stat().st_size} bytes) | {path.suffix or 'extensionless'} |")
            continue
        content = path.read_text(encoding="utf-8-sig", errors="replace")
        lines = content.splitlines()
        inventory.append(f"| `{relative}` | {len(lines)} | {path.suffix} |")
        for line_number, line in enumerate(lines, 1):
            found = sorted(set(MARKERS.findall(line)))
            if found:
                # Inventory marker names only; never copy arbitrary credential-bearing lines.
                markers.append(f"| `{relative}:{line_number}` | {', '.join(found)} |")
        if path.suffix == ".py":
            try:
                tree = ast.parse(content)
            except SyntaxError as exc:
                parse_errors.append(f"`{relative}:{exc.lineno}`")
                continue
            if relative.startswith("tests/"):
                test_functions += sum(
                    isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_")
                    for node in ast.walk(tree)
                )
    route_rows = []
    for context in iter_route_contexts(app.routes):
        route = context.original_route
        if not isinstance(route, APIRoute):
            continue
        effective = context._effective_route
        names = sorted(dependencies(effective.dependant))
        location = f"{route.endpoint.__module__.replace('.', '/')}.py:{route.endpoint.__code__.co_firstlineno}"
        for method in sorted(route.methods):
            route_rows.append(f"| {method} | `{context.path}` | `{location}` | {', '.join(names) or 'none declared'} | UNKNOWN |")
    tables = []
    for table in sorted(Base.metadata.tables.values(), key=lambda item: item.name):
        direct = "organization_id" in table.columns
        fks = sorted(str(fk.target_fullname) for fk in table.foreign_keys)
        tables.append(f"| `{table.name}` | {'DIRECT candidate' if direct else 'see tenant matrix'} | {', '.join(fks) or '-'} | UNKNOWN | UNKNOWN |")
    discovery = [
        "# Autonomous audit 01 — discovery", "", "Date: 2026-10-03.", "",
        "Generated by `python -m scripts.audit_inventory`. Static inventory, not exhaustive semantic review.",
        "No .env, dependency cache, worktree copy or credentials read; no database connection or app lifespan.",
        "This command's two generated output files are excluded to prevent self-amplifying marker inventories.",
        "Binary/unknown formats and dependency lockfiles are listed by metadata only, not claimed to be content-reviewed.",
        "Dead code, duplicate semantics, commented-out features and correctness of every function: UNKNOWN.",
        f"Inventoried files: {len(files)}; ORM tables: {len(tables)}; API operations: {len(route_rows)}.",
        f"AST test function definitions: {test_functions}; parametrized pytest case count is different.",
        f"Python syntax errors: {', '.join(parse_errors) or 'none found by AST parse'}.", "",
        "## File counts", "", "| Top-level area | Files |", "|---|---:|",
        *[f"| `{key}` | {value} |" for key, value in sorted(counts.items())],
        "", "## Files (excluding this command's generated outputs)", "",
        "| File | Lines | Kind |", "|---|---:|---|", *inventory,
        "", "## Marker locations (not confirmed bugs)", "",
        "| Source/line | Markers |", "|---|---|", *markers,
    ]
    (ROOT / "docs" / "AUTONOMOUS_AUDIT_01_DISCOVERY.md").write_text("\n".join(discovery) + "\n", encoding="utf-8")
    security = [
        "# Autonomous audit 03 — security inventory", "", "Date: 2026-10-03.", "",
        "Generated route dependency inventory; declaring a dependency does not prove authorization.",
        "Filter tenant, exploitable behavior and database policies require separate specialist/live tests.",
        "See `SECURITY_REPORT.md` for verified specialist findings and coverage limits.", "",
        "## All API operations currently registered", "",
        "| Method | Path | Handler source | Dependency call names | Tenant filter verified |",
        "|---|---|---|---|---|", *route_rows, "",
        "## All ORM tables (not a live catalog)", "",
        "| Table | Tenant class | Foreign-key targets | Live RLS | Live policies |",
        "|---|---|---|---|---|", *tables,
        "", "## Corrections and findings", "",
        "See `AUTONOMOUS_AUDIT_05_FIXES.md` and `SECURITY_REPORT.md`; no live RLS state is inferred here.",
    ]
    (ROOT / "docs" / "AUTONOMOUS_AUDIT_03_SECURITY.md").write_text("\n".join(security) + "\n", encoding="utf-8")
    print(f"GENERATED discovery and security inventories: files={len(files)}, operations={len(route_rows)}, tables={len(tables)}")


if __name__ == "__main__":
    generate()
