#!/bin/bash
# Runs the exact same 4 batches as .circleci/config.yml's "Run the full
# api/ test suite" step, for reproducing a CI result locally (or running
# the full suite as part of a coherence audit) without hand-copying the
# pytest invocations out of the YAML. Keep the file lists here in sync
# with .circleci/config.yml if either one changes.
set +e
RC=0
echo "--- batch 1/4 ---"
pytest -q tests/test_auth_api.py tests/test_auth_security.py tests/test_config.py tests/test_email_service.py tests/test_recovery_codes.py tests/test_password_strength.py tests/test_password_similarity.py tests/test_storage.py tests/test_audit_log.py tests/test_security_alerts.py tests/test_monitoring.py tests/test_trusted_ips_and_geoip.py tests/test_roles_and_permissions.py tests/test_organizations.py tests/test_organization_members.py tests/test_workspaces.py tests/test_resource_permissions.py tests/test_teams.py tests/test_invitations.py tests/test_quotas.py tests/test_user_limits.py tests/test_usage.py tests/test_organization_settings.py tests/test_organization_branding.py tests/test_custom_domains.py tests/test_ssl_certificates.py tests/test_domain_verification.py tests/test_email_domains.py tests/test_white_label.py tests/test_pdf_extraction.py tests/test_docx_extraction.py tests/test_txt_extraction.py tests/test_markdown_extraction.py tests/test_html_extraction.py tests/test_csv_extraction.py tests/test_json_extraction.py tests/test_xml_extraction.py tests/test_epub_extraction.py tests/test_url_fetching.py tests/test_url_extraction.py tests/test_sitemap_extraction.py tests/test_github_extraction.py tests/test_google_drive_extraction.py tests/test_notion_extraction.py tests/test_confluence_extraction.py tests/test_onedrive_extraction.py tests/test_zip_extraction.py tests/test_metadata_normalization.py tests/test_document_progress.py tests/test_reindex.py tests/test_document_audit.py tests/test_document_status.py tests/test_document_duplicates.py tests/test_document_modification_check.py tests/test_external_sources.py tests/test_reindex_schedules.py tests/test_batch_jobs.py tests/test_text_cleaning.py tests/test_text_normalization.py tests/test_table_transformation.py tests/test_image_extraction.py tests/test_ocr.py tests/test_language_detection.py tests/test_headings_extraction.py tests/test_structure_detection.py tests/test_metadata_enrichment.py tests/test_chunking.py tests/test_semantic_chunking.py
RC=$((RC + $?))
echo "--- batch 2/4 ---"
pytest -q tests/test_markdown_chunking.py tests/test_code_chunking.py tests/test_sentence_chunking.py tests/test_paragraph_chunking.py tests/test_parent_child_chunking.py tests/test_chunk_config.py tests/test_embedding_config.py tests/test_retrieval_config.py tests/test_retrieval_pipeline.py tests/test_search.py tests/test_llm_providers.py tests/test_metadata_filtering.py tests/test_semantic_filtering.py tests/test_duplicate_removal.py tests/test_mmr.py tests/test_query_rewriting.py tests/test_hyde.py tests/test_multi_query.py tests/test_context_compression.py tests/test_embedding_providers.py tests/test_llm_config.py tests/test_agent_orchestrator.py tests/test_tools.py tests/test_tool_selection.py tests/test_tool_permissions.py tests/test_tool_timeout.py tests/test_tool_budget.py tests/test_retry.py tests/test_fallback.py tests/test_parallel_tools.py tests/test_tool_validation.py tests/test_human_approval.py tests/test_agent_memory.py tests/test_conversations.py tests/test_task_planning.py tests/test_agent_traces.py tests/test_search_kb_tool.py tests/test_github_tools.py tests/test_web_search.py tests/test_sql_tool.py tests/test_calculator_tool.py tests/test_url_reader.py tests/test_calendar_tools.py tests/test_email_tools.py tests/test_human_escalation.py tests/test_custom_tools.py tests/test_agents.py tests/test_agent_prompts.py tests/test_agent_models.py tests/test_agent_knowledge_base.py tests/test_agent_tools.py tests/test_agent_memory_config.py tests/test_agent_permissions.py tests/test_agent_guardrails.py tests/test_agent_api_keys.py tests/test_workflows.py tests/test_workflow_triggers.py tests/test_template_rendering.py tests/test_workflow_block_llm.py tests/test_workflow_block_rag.py tests/test_workflow_block_search.py tests/test_workflow_block_http.py tests/test_workflow_block_condition.py tests/test_workflow_block_code.py tests/test_workflow_block_human.py tests/test_workflow_block_email.py tests/test_workflow_block_calendar.py tests/test_workflow_block_database.py
RC=$((RC + $?))
echo "--- batch 3/4 ---"
pytest -q tests/test_workflow_versions.py tests/test_citations.py tests/test_generation.py tests/test_citation_documents.py tests/test_citation_location.py tests/test_citation_url.py tests/test_citation_chunk.py tests/test_citation_relevance.py tests/test_citation_passage.py tests/test_citation_preview.py tests/test_citation_secondary.py tests/test_response_confidence.py tests/test_claim_extraction.py tests/test_text_similarity.py tests/test_contradiction_detection.py tests/test_source_consistency.py tests/test_confidence_estimation.py tests/test_claim_verification.py tests/test_hallucination_detector.py tests/test_groundedness.py tests/test_response_quality.py tests/test_response_detail_endpoint.py tests/test_agent_citation_required.py tests/test_agent_context_only.py tests/test_agent_idk.py tests/test_unsupported_claims.py tests/test_faithfulness.py tests/test_quality_dashboard.py tests/test_question_difficulty.py tests/test_evaluation_datasets.py tests/test_evaluation_datasets_endpoints.py tests/test_question_sets.py tests/test_question_sets_endpoints.py tests/test_ground_truth_answers.py tests/test_ground_truth_documents.py tests/test_benchmark_versions.py tests/test_benchmark_versions_endpoints.py tests/test_retrieval_metrics.py tests/test_answer_quality_metrics.py tests/test_evaluation_results.py tests/test_evaluation_results_endpoints.py tests/test_evaluation_comparisons.py tests/test_evaluation_comparisons_endpoints.py tests/test_context_relevance.py tests/test_citation_correctness.py tests/test_hallucination_rate.py tests/test_latency_metrics.py tests/test_token_usage.py tests/test_cost_tracking.py tests/test_evaluation_jobs.py tests/test_evaluation_jobs_endpoints.py tests/test_manual_evaluations.py tests/test_manual_evaluations_endpoints.py tests/test_comparison_jobs.py tests/test_comparison_jobs_endpoints.py tests/test_regression_detection.py tests/test_regression_detection_endpoints.py tests/test_regression_thresholds.py tests/test_regression_thresholds_endpoints.py tests/test_deployment_evaluations.py tests/test_deployment_evaluations_endpoints.py tests/test_ab_tests.py tests/test_ab_tests_endpoints.py tests/test_streaming.py tests/test_code_highlighter.py tests/test_markdown_renderer.py tests/test_message_actions.py tests/test_conversation_management.py
RC=$((RC + $?))
echo "--- batch 4/4 ---"
pytest -q tests/test_conversation_export.py tests/test_conversation_sharing.py tests/test_suggested_questions.py tests/test_i18n.py tests/test_voice_providers.py tests/test_voice_messages_and_settings.py tests/test_telephony.py tests/test_public_api.py tests/test_api_key_management.py tests/test_webhooks.py tests/test_inbound_webhooks.py tests/test_api_versioning.py tests/test_widget.py tests/test_chat_integrations.py tests/test_document_extraction.py tests/test_documents.py tests/test_google_docs_integration.py tests/test_notion_integration.py tests/test_confluence_integration.py tests/test_onedrive_integration.py tests/test_zip_integration.py tests/test_document_batch_integration.py tests/test_postgres_integration.py tests/test_rbac_integration.py tests/test_oauth_logic_integration.py tests/test_rate_limiting_integration.py tests/test_avatar_storage_integration.py tests/test_branding_storage_integration.py tests/test_dns_verification_integration.py tests/test_acme_integration.py tests/test_ssl_certificate_renewal_integration.py tests/test_domain_verification_integration.py tests/test_email_domains_integration.py tests/test_documents_integration.py tests/test_url_fetching_integration.py tests/test_sitemap_extraction_integration.py tests/test_sitemap_integration.py tests/test_github_extraction_integration.py tests/test_github_integration.py tests/test_google_drive_extraction_integration.py tests/test_google_drive_integration.py tests/test_notion_extraction_integration.py tests/test_onedrive_extraction_integration.py tests/test_geo_adaptive_rate_limit_integration.py tests/test_webauthn_integration.py tests/test_jwt_key_rotation_integration.py tests/test_enterprise_sso_integration.py tests/test_celery_integration.py tests/test_e2e_lifecycle.py tests/test_connections.py tests/test_mappings.py tests/test_transformations.py tests/test_sales_models.py tests/test_notifications_datadog_grafana.py tests/test_plugins.py tests/test_plugin_marketplace.py tests/test_plugin_reviews.py tests/test_plugin_sandbox.py tests/backend/ab-tests tests/backend/analytics tests/backend/autonomous tests/backend/fine-tuning tests/backend/media tests/backend/whitelabel tests/docs tests/test_admin_dashboard.py tests/test_admin_organizations.py tests/test_admin_subscriptions.py tests/test_admin_users_management.py tests/test_audit_extensions.py tests/test_billing.py tests/test_compliance.py tests/test_deployment.py tests/test_encryption.py tests/test_observability.py tests/test_rbac_custom.py tests/test_security_scan.py
RC=$((RC + $?))
echo "ALL_BATCHES_RC=$RC"
