"""
Audit finding 15 -- keeps a user's most recent password hashes so a new
password can be checked against them (api/security/password_history.py),
independent of `User.hashed_password` itself (the CURRENT password, never
stored here twice -- see that module's docstring for how the two are
combined at check time).

Only the most recent PASSWORD_HISTORY_SIZE rows per user are ever kept
(pruned by api/security/password_history.py's record_password_change() on
every write) -- this table is a short reuse-check window, not a permanent
password audit log.

`sequence` (migration 0019) -- a monotonic counter per user, NOT
`created_at`, is what "most recent N rows" actually orders by.
`created_at` alone flaked in real CI: two rows written in fast succession
can share the same microsecond-truncated timestamp, and `id` (a random
UUID v4, not time-ordered) can't break that tie meaningfully -- ties on
`created_at` made Postgres's row order for those rows genuinely
undefined, so which row got pruned as "stale" varied run to run.

`sequence` is assigned explicitly by record_password_change() (next
integer per user_id), NOT a DB-native IDENTITY/serial column -- a first
attempt used Postgres `GENERATED BY DEFAULT AS IDENTITY`, which broke
the entire fast test suite: that suite builds its schema straight from
these model definitions via `Base.metadata.create_all()` (no Alembic),
and SQLite has no equivalent for an identity column on anything but an
INTEGER PRIMARY KEY. Computing the value in application code instead
works identically on both backends -- the same "compute a value in
code, let a unique constraint catch a genuine collision" shape as
api/security/organizations.py's generate_unique_slug.
"""

import datetime as dt
import uuid

from sqlalchemy import BigInteger, DateTime, ForeignKey, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from api.database import Base


class PasswordHistory(Base):
    __tablename__ = "password_history"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    # Same bcrypt hash format as User.hashed_password -- a stored former
    # password is exactly as sensitive as the current one, salted and
    # slow to brute-force the same way.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)
    sequence: Mapped[int] = mapped_column(BigInteger, nullable=False)

    __table_args__ = (
        UniqueConstraint("user_id", "sequence", name="uq_password_history_user_sequence"),
    )
