"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { api } from "@/lib/api";
import { fetchDisplayCurrency } from "@/lib/currency";
import en from "@/lib/locales/en.json";

// Bundled copies of the translations (generated by scripts/sync_frontend_locales.py from /locales). English is in the main bundle so the very
// first render already has every text; the other languages are loaded on demand. The API response (below) overrides them once it arrives.
const BUNDLED: Record<string, () => Promise<Record<string, string>>> = {
  en: async () => en,
  fr: async () => (await import("@/lib/locales/fr.json")).default,
  es: async () => (await import("@/lib/locales/es.json")).default,
  de: async () => (await import("@/lib/locales/de.json")).default,
  pt: async () => (await import("@/lib/locales/pt.json")).default,
  ar: async () => (await import("@/lib/locales/ar.json")).default,
};

// Real fix for a real bug found by manual QA: the language switcher
// used to only change the flag shown, then reload the page -- but
// GET /i18n/translations/{language} only ever served the `common`
// category (a backend bug, now fixed in api/routers/i18n.py), and no
// frontend component ever actually READ any translated string at
// all -- every UI label was hardcoded English JSX text. This real
// context is the missing piece: it fetches the real, merged
// translation dict once per language and exposes a real `t(key)`
// every component below can call, reactively (no page reload needed
// to see the new language).
interface I18nContextValue {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const I18nContext = createContext<I18nContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

const LANGUAGE_STORAGE_KEY = "ui_language";
const SUPPORTED_LANGUAGES = Object.keys(BUNDLED);

function readStoredLanguage(): string | null {
  try {
    const value = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return value && SUPPORTED_LANGUAGES.includes(value) ? value : null;
  } catch {
    return null;
  }
}

function browserLanguage(): string | null {
  const code = (navigator.language || "").slice(0, 2).toLowerCase();
  return SUPPORTED_LANGUAGES.includes(code) ? code : null;
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>("en");
  const [translations, setTranslations] = useState<Record<string, string>>(en);

  // Language order: the visitor's own earlier choice, then the browser language (when we ship it), then the backend's stored preference, else English.
  useEffect(() => {
    const stored = readStoredLanguage();
    const browser = browserLanguage();
    const initial = stored ?? browser;
    if (initial && initial !== "en") {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- the browser language is only readable after mount (server and first client render stay in English)
      setLanguageState(initial);
      return;
    }
    if (stored || browser) return;
    // Neither a saved choice nor a browser language we ship: use where the visitor is (the same lookup that picks the price currency).
    void fetchDisplayCurrency().then((answer) => {
      if (answer?.language && SUPPORTED_LANGUAGES.includes(answer.language) && answer.language !== "en") setLanguageState(answer.language);
    });
  }, []);

  useEffect(() => {
    let cancelled = false;
    document.documentElement.lang = language;
    const bundled = (BUNDLED[language] ?? BUNDLED.en)().catch(() => en as Record<string, string>);
    // 1. instant: the bundled language. 2. later: the API's version on top of it (it can carry newer or customised strings).
    void bundled.then((texts) => { if (!cancelled) setTranslations(texts); });
    void api
      .get<Record<string, string>>(`/i18n/translations/${language}`)
      .then(async (data) => { const texts = await bundled; if (!cancelled) setTranslations({ ...texts, ...data }); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [language]);

  const setLanguage = useCallback((next: string) => {
    setLanguageState(next);
    try { window.localStorage.setItem(LANGUAGE_STORAGE_KEY, next); } catch { /* storage unavailable: the choice just lasts for this visit */ }
    void api.post("/i18n/language", { language: next }).catch(() => {});
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      const raw = translations[key] ?? (en as Record<string, string>)[key] ?? key;
      if (!params) return raw;
      return Object.entries(params).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), raw);
    },
    [translations],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useTranslation() {
  return useContext(I18nContext);
}
